### ISSUE TITLE
El titulo de esto no me gusta

### ISSUE THREAD

**Issue by kiptetole** [iesgrancapitan-entornos/practica-5-github-issues-kiquevedder87#1]
No expresa el sentimiento de la progrmacion
la programacion esta: Triste

**Comment by jaimerabasco** [comment]
Solo hay 1 issue y esta sin cerrar. La práctica son 3 más. @kiquevedder87 @kiptetole

**Comment by kiquevedder87** [comment]
Para estar todos contentos, cerremos pues.
